mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.Detailview.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('creat-question/', views.createQuestion, name="create_question"),
    path('<str:pk>/update-question/', views.updateQuiz, name="update_question"),
    path('<str:pk>/create-choice/', views.createChoice, name="create-choice"),
    path('<str:pk>/delete-question/', views.deleteQuiz, name="delete_question")
]

mysite/polls/models.py
import datetime
from django.contrib import admin
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    now = datetime.datetime.now()
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

# Create your models here.

mysite/polls/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect,render
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from .form import Questionform, Choiceform
from .models import Choice,Question

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        """Return the last five published questions. """
        return  Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')

class Detailview(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        #redisplay the question voting form
        return render(request, 'polls/detail.html',{
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        #always return HttpResponseRedirect after succesfully dealing
        #with POST data This prevents data
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
def createQuestion(request):
    form = Questionform()
    if request.method == 'POST':
        form = Questionform(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/')
            
    context = {"form":form}
    return render(request, 'polls/form.html', context)


def createChoice(request, pk):
    choice = Choice.objects.get(id=pk)
    form = Choiceform(instance=choice)
    if request.method == 'POST':
        form = Choiceform(request.POST, instance=choice)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {'form':form}
    return render(request, 'polls/form.html', context)

def updateQuiz(request, pk):
    question = Question.objects.get(id=pk)
    form = Questionform(instance=question)
    if request.method == 'POST':
        form = Questionform(request.POST, instance=question)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {'form':form}
    return render(request, 'polls/form.html', context)

def deleteQuiz(request,pk):
    question = Question.objects.get(id=pk)
    if request.method == 'POST':
        question.delete()
        return redirect('/')
    return render(request, 'polls/delete.html', {"obj":question})
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})
# Create your views here.

mysite/polls/templates/polls/delete.html
<form method="POST" action="">
    {% csrf_token %}
    <p>Are you sure you want to delete "<u><strong>{{obj}}</strong></u>"?</p>
    <a href="{{request.META.HTTP_REFERER}}" style="text-decoration: none">No thanks</a>
    <input type="submit" value="Yes">
</form>

mysite/polls/templates/polls/detail.html
<html>
<body style="background-color: black">
    <form action="{% url 'polls:vote' question.id %}" method="post" style="background-color: rgb(3, 37, 46)">
        {% csrf_token %}
        <fieldset style="color: blue;">
            <legend style="color: red;"><h1>{{ question.question_text }}</h1></legend>
            {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" style="color: green;">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}
            </label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote" style="color: green;">
    </form>
</body>
</html>

mysite/polls/templates/polls/form.html
<a href="/">
    Home
</a>
<h3>Write your question.</p>
<div>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit" />
    </form>
</div>

mysite/polls/templates/polls/index.html
<html>
<head>
    <title>
        Django page
    </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>
<h1>These are the questions</h1>
<body>
<div class="container">
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
        </li>
        <div  class="change">
            <a href="{% url 'polls:update_question' question.id %}" style="text-decoration: none">Edit</a>
            <a href="{% url 'polls:delete_question' question.id %}" style="text-decoration: none">Delete</a>
            <a href="{% url 'polls:create-choice' question.id %}" style="text-decoration: none">Edit choice</a>
        </div>
        <hr>
        {% endfor %}
        <div class="back">
        <a href="{% url 'polls:create_question'  %}  " style="text-decoration: none">
            <h3>Add question</h3>
        </a>
        </div>
        <h1>The end</h1>
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</div>
</body>
</html>

mysite/polls/templates/polls/results.html
<html>
<a href="{% url 'polls:index'  %}">
    <h3>HOME</h3>
</a>
<h1>{{ question.question_text }}</h1>
<hr>
<body style ="background-color: grey">
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }}
        vote {{ choice.votes |pluralize }}</li>
    {% endfor %}
</ul>
    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>